// src/components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/styling-utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
        className,
      )}
      {...props}
    />
  );
}

export { Input };

// apps/web-svelte/src/lib/components/ui/Input.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  interface Props {
    value?: string | number;
    oninput?: (e: Event) => void;
    onchange?: (e: Event) => void;
    onblur?: (e: FocusEvent) => void;
    type?: "text" | "number" | "email" | "password" | "search" | "date" | "tel" | "url";
    placeholder?: string;
    disabled?: boolean;
    readonly?: boolean;
    required?: boolean;
    id?: string;
    name?: string;
    step?: string | number;
    min?: string | number;
    max?: string | number;
    autocomplete?: HTMLInputElement["autocomplete"];
    class?: string;
  }

  let {
    value = $bindable(),
    oninput,
    onchange,
    onblur,
    type = "text",
    placeholder,
    disabled = false,
    readonly = false,
    required = false,
    id,
    name,
    step,
    min,
    max,
    autocomplete,
    class: className,
  }: Props = $props();
</script>

<input
  {type}
  {placeholder}
  {disabled}
  {readonly}
  {required}
  {id}
  {name}
  {step}
  {min}
  {max}
  {autocomplete}
  bind:value
  {oninput}
  {onchange}
  {onblur}
  class={cn(
    "h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-emerald-500 focus:ring-offset-1 focus:outline-none",
    "dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100 dark:placeholder:text-slate-500",
    "disabled:cursor-not-allowed disabled:opacity-50",
    className
  )}
/>
