// src/modules/shared/components/Navigation.tsx
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { useAuth } from "@/lib/AuthContext";
import { signOut } from "@/lib/firebase/firebase";
import { NavLink } from "@/modules/shared/components/NavLink";
import { Link, useNavigate } from "@tanstack/react-router";
import { LogOut, Menu } from "lucide-react";
import { useState } from "react";

type ValidRoute =
  | "/"
  | "/transactions"
  | "/login"
  | "/admin"
  | "/admin/categories";

interface NavItem {
  to: ValidRoute;
  label: string;
  exact?: boolean;
}

const NAV_ITEMS: NavItem[] = [
  { to: "/transactions", label: "Transactions" },
  { to: "/admin", label: "Admin" },
];

export function Navigation() {
  const [open, setOpen] = useState(false);
  const { isAuthenticated, userData } = useAuth();
  const navigate = useNavigate();

  const isAdmin = userData?.role === "admin";

  const handleLogout = async () => {
    await signOut();
    navigate({ to: "/" });
  };

  return (
    <header className="bg-gray-100 shadow">
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex-shrink-0 flex items-center">
            <Link to="/" className="text-xl font-bold text-gray-800">
              Portfelik
            </Link>
          </div>

          {/* Desktop navigation */}
          <div className="hidden md:flex items-center">
            <div className="flex space-x-8">
              <NavLinks isAdmin={isAdmin} />
            </div>
            <div className="ml-8">
              {isAuthenticated ? (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleLogout}
                  className="flex items-center gap-2"
                >
                  <LogOut className="h-4 w-4" />
                  Logout
                </Button>
              ) : (
                <Button variant="outline" size="sm" asChild>
                  <Link to="/login">Login</Link>
                </Button>
              )}
            </div>
          </div>

          {/* Mobile menu button */}
          <div className="md:hidden flex items-center">
            <Sheet open={open} onOpenChange={setOpen}>
              <SheetTrigger asChild>
                <button className="inline-flex items-center justify-center p-2 rounded-md text-gray-700 hover:text-blue-600 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500">
                  <span className="sr-only">Open main menu</span>
                  <Menu className="h-6 w-6" />
                </button>
              </SheetTrigger>
              <SheetContent>
                <div className="mt-6 flex flex-col gap-4">
                  <MobileNavLinks
                    onNavigate={() => setOpen(false)}
                    isAdmin={isAdmin}
                  />
                  <div className="mt-4">
                    {isAuthenticated ? (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          handleLogout();
                          setOpen(false);
                        }}
                        className="flex items-center gap-2 w-full"
                      >
                        <LogOut className="h-4 w-4" />
                        Logout
                      </Button>
                    ) : (
                      <Button
                        variant="outline"
                        size="sm"
                        asChild
                        className="w-full"
                      >
                        <Link to="/login" onClick={() => setOpen(false)}>
                          Login
                        </Link>
                      </Button>
                    )}
                  </div>
                </div>
              </SheetContent>
            </Sheet>
          </div>
        </div>
      </nav>
    </header>
  );
}

function NavLinks({ isAdmin }: { isAdmin?: boolean }) {
  // Filter out admin routes if user is not an admin
  const filteredNavItems = NAV_ITEMS.filter(
    (item) => !item.to.startsWith("/admin") || isAdmin,
  );

  return (
    <>
      {filteredNavItems.map((item) => (
        <NavLink
          key={item.to}
          to={item.to}
          activeOptions={item.exact ? { exact: true } : undefined}
          className="transition-colors duration-200 hover:text-blue-600"
        >
          {item.label}
        </NavLink>
      ))}
    </>
  );
}

function MobileNavLinks({
  onNavigate,
  isAdmin,
}: {
  onNavigate: () => void;
  isAdmin?: boolean;
}) {
  // Filter out admin routes if user is not an admin
  const filteredNavItems = NAV_ITEMS.filter(
    (item) => !item.to.startsWith("/admin") || isAdmin,
  );

  return (
    <>
      {filteredNavItems.map((item) => (
        <NavLink
          key={item.to}
          to={item.to}
          isMobile
          onNavigate={onNavigate}
          activeOptions={item.exact ? { exact: true } : undefined}
        >
          {item.label}
        </NavLink>
      ))}
    </>
  );
}

// apps/web-svelte/src/lib/components/Navigation.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { supabase } from "$lib/supabase";
  import { cn } from "$lib/utils";
  import type { Profile } from "$lib/types";
  import * as m from "$lib/paraglide/messages";
  import { Wallet, ShoppingBasket, Settings, ShieldCheck, LogOut } from "lucide-svelte";
  import NotificationsPopover from "$lib/components/ui/NotificationsPopover.svelte";

  interface Props {
    profile: Profile | null;
  }
  let { profile }: Props = $props();

  const navItems = [
    { href: "/transactions", label: m.nav_transactions(), icon: Wallet },
    { href: "/shopping-lists", label: m.nav_shopping_lists(), icon: ShoppingBasket },
    { href: "/settings", label: m.nav_settings(), icon: Settings },
  ];

  const isActive = (href: string) => $page.url.pathname.startsWith(href);

  async function signOut() {
    await supabase.auth.signOut();
    goto("/login");
  }
</script>

<!-- Desktop top bar -->
<header
  class="fixed inset-x-0 top-0 z-50 hidden h-14 items-center gap-6 border-b border-zinc-200 bg-white px-6 md:flex"
>
  <span class="mr-2 shrink-0 font-semibold text-zinc-900">{m.app_name()}</span>

  <nav aria-label={m.nav_main()} class="flex items-center gap-1">
    {#each navItems as item (item.href)}
      {@const Icon = item.icon}
      <a
        href={item.href}
        aria-current={isActive(item.href) ? "page" : undefined}
        class={cn(
          "flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:outline-none",
          isActive(item.href)
            ? "bg-zinc-100 text-zinc-900"
            : "text-zinc-500 hover:bg-zinc-50 hover:text-zinc-900"
        )}
      >
        <Icon size={15} aria-hidden="true" />
        {item.label}
      </a>
    {/each}

    {#if profile?.role === "admin"}
      <a
        href="/admin"
        aria-current={isActive("/admin") ? "page" : undefined}
        class={cn(
          "flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:outline-none",
          isActive("/admin")
            ? "bg-zinc-100 text-zinc-900"
            : "text-zinc-500 hover:bg-zinc-50 hover:text-zinc-900"
        )}
      >
        <ShieldCheck size={15} aria-hidden="true" />
        {m.nav_admin()}
      </a>
    {/if}
  </nav>

  <div class="ml-auto flex items-center gap-2">
    {#if profile}
      <span class="hidden text-xs text-zinc-400 lg:block">{profile.email}</span>
    {/if}
    <NotificationsPopover />
    <button
      type="button"
      onclick={signOut}
      class="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm text-zinc-500 transition-colors hover:bg-zinc-50 hover:text-zinc-900 focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:outline-none"
    >
      <LogOut size={15} aria-hidden="true" />
      {m.nav_sign_out()}
    </button>
  </div>
</header>

<!-- Mobile bottom tab bar -->
<nav
  aria-label={m.nav_main()}
  class="fixed inset-x-0 bottom-0 z-50 flex border-t border-zinc-200 bg-white md:hidden"
  style="padding-bottom: env(safe-area-inset-bottom)"
>
  {#each navItems as item (item.href)}
    {@const Icon = item.icon}
    <a
      href={item.href}
      aria-current={isActive(item.href) ? "page" : undefined}
      class={cn(
        "flex min-h-[56px] flex-1 flex-col items-center justify-center gap-0.5 py-2 text-[10px] font-medium transition-colors",
        isActive(item.href) ? "text-zinc-900" : "text-zinc-400"
      )}
    >
      <Icon size={22} aria-hidden="true" />
      {item.label}
    </a>
  {/each}

  <!-- Notifications bell — sits between Settings and Admin -->
  <div class="relative flex min-h-[56px] flex-1 items-center justify-center">
    <NotificationsPopover
      placement="bottom"
      buttonClass="relative flex flex-col items-center justify-center gap-0.5 py-2 text-[10px] font-medium text-zinc-400 transition-colors min-h-[56px] w-full"
    />
  </div>

  {#if profile?.role === "admin"}
    <a
      href="/admin"
      aria-current={isActive("/admin") ? "page" : undefined}
      class={cn(
        "flex min-h-[56px] flex-1 flex-col items-center justify-center gap-0.5 py-2 text-[10px] font-medium transition-colors",
        isActive("/admin") ? "text-zinc-900" : "text-zinc-400"
      )}
    >
      <ShieldCheck size={22} aria-hidden="true" />
      {m.nav_admin()}
    </a>
  {/if}
</nav>
