// apps/web-svelte/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { Snippet } from "svelte";

  interface Props {
    variant: "paid" | "upcoming" | "overdue" | "draft" | "shared" | "outline";
    class?: string;
    children: Snippet;
  }

  let { variant, class: className, children }: Props = $props();

  const variants: Record<string, string> = {
    paid: "bg-emerald-50 text-emerald-700 dark:bg-emerald-900/15 dark:text-emerald-400",
    upcoming: "bg-amber-50 text-amber-700 dark:bg-amber-900/15 dark:text-amber-400",
    overdue: "bg-rose-50 text-rose-700 dark:bg-rose-900/15 dark:text-rose-400",
    draft: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400",
    shared: "bg-blue-50 text-blue-700 dark:bg-blue-900/15 dark:text-blue-400",
    outline:
      "border border-slate-200 bg-transparent text-slate-600 dark:border-slate-700 dark:text-slate-300",
  };
</script>

<span
  class={cn(
    "inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium",
    variants[variant],
    className
  )}
>
  {@render children()}
</span>

// src/components/ui/badge.tsx
import { cn } from "@/lib/styling-utils";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

const badgeVariants = cva(
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
        destructive:
          "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
        outline: "text-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  );
}

export { Badge, badgeVariants };
